---
title: "Proyecto ICD"
author: "Pedro Paiva, Krystle Salazar"
date: "11 de agosto de 2015"
output: pdf_document
---

Introducci贸n
============



Preprocesamiento
================

```{r echo=FALSE, cache=TRUE}
library(tm)
library(SnowballC)
library(wordcloud)

# # Leyendo posts de user 1 y 2 con codificaci贸n ANSI
# data <- read.table("data.csv", header = TRUE, sep = ";", row.names = 1, encoding = "ANSI",
#                       nrows = 2000)
# # Leyendo todos los posts con codificaci贸n UTF-8
# posts <- read.table("data.csv", header = TRUE, sep = ";", row.names = 1, encoding = "UTF-8")
# 
# # Se quitan los posts de user 1 y 2 con UTF-8 para reemplazarlos con el ANSI
# posts <- posts[-c(1:2000),]
# posts <- rbind(data, posts)

posts <- read.table("data.csv", header = TRUE, sep = ";", row.names = 1, encoding = "ANSI")

# Ignorando las filas sin posts
posts <- na.omit(posts)

# Divisi贸n de data frames por usuarios
u1 <- posts[which(posts$id_user == 1),]
u2 <- posts[which(posts$id_user == 2),]
u3 <- posts[which(posts$id_user == 3),]
u4 <- posts[which(posts$id_user == 4),]
u5 <- posts[which(posts$id_user == 5),]

# Creando los Corpus de cada usuario
myCorpus1 <- Corpus(VectorSource(u1$post))
myCorpus2 <- Corpus(VectorSource(u2$post))
myCorpus3 <- Corpus(VectorSource(u3$post))
myCorpus4 <- Corpus(VectorSource(u4$post))
myCorpus5 <- Corpus(VectorSource(u5$post))
myCorpus <- Corpus(VectorSource(posts$post))

# Funciones de limpieza
removeURL <- function(x){
  gsub("http[[:alnum:]]*", "", x)
  gsub("www[[:alnum:]]*", "", x)
}
removeLaugh <- function(x){
  gsub("\b(?:a*(?:ja)+j?|(?:l+o+)+l+)\b", "", x)
  gsub("\b(?:a*(?:ha)+h?|(?:l+o+)+l+)\b", "", x)
}

# add extra stop words
myStopwords <- c(stopwords('english'), stopwords('spanish'), "xd", "xD", "like", "RT", "etc",
                 "csm", "para", "ser", "wtf", "mas", "una", "nos", "est","esto", "este",
                 "jajaja", "jajajaja", "si")
skipWords <- function(x) removeWords(x, myStopwords)

cleanFuns <- list(PlainTextDocument, tolower, removePunctuation, removeNumbers, removeURL,
                  skipWords, removeLaugh, stemDocument)

# Limpieza de cada corpus
cleanCorpus = function(myCorpus){
  myCorpus_aux <- tm_map(myCorpus, FUN = tm_reduce, tmFuns = cleanFuns, lazy = T)
  myCorpus <- tm_map(myCorpus_aux, FUN = removeWords, myStopwords, lazy = F)
}

cleanCorpus(myCorpus1)
cleanCorpus(myCorpus2)
cleanCorpus(myCorpus3)
cleanCorpus(myCorpus4)
cleanCorpus(myCorpus5)
cleanCorpus(myCorpus)

```

Individuos y palabras
=====================

```{r, echo=FALSE, cache=TRUE}
# Matriz Term-Document para cada usuario
myTdm1 <- TermDocumentMatrix(myCorpus1, control=list(wordLengths=c(2,Inf)))
myTdm2 <- TermDocumentMatrix(myCorpus2, control=list(wordLengths=c(2,Inf)))
myTdm3 <- TermDocumentMatrix(myCorpus3, control=list(wordLengths=c(2,Inf)))
myTdm4 <- TermDocumentMatrix(myCorpus4, control=list(wordLengths=c(2,Inf)))
myTdm5 <- TermDocumentMatrix(myCorpus5, control=list(wordLengths=c(2,Inf)))
myTdm <- TermDocumentMatrix(myCorpus, control=list(wordLengths=c(2,Inf)))

# remove sparse terms usuario 1
myTdmAux <- removeSparseTerms(myTdm1, sparse=0.985)
#View(as.matrix(myTdmAux1))
# count frequency 
temp <- as.matrix(myTdmAux)
FreqMat1 <- data.frame(Term = rownames(temp), Freq = rowSums(temp))
row.names(FreqMat1) <- NULL

# remove sparse terms usuario 2
myTdmAux <- removeSparseTerms(myTdm2, sparse=0.985)
# count frequency 
temp <- as.matrix(myTdmAux)
FreqMat2 <- data.frame(Term = rownames(temp), Freq = rowSums(temp))
row.names(FreqMat2) <- NULL

# remove sparse terms usuario 3
myTdmAux <- removeSparseTerms(myTdm3, sparse=0.985) 
# count frequency 
temp <- as.matrix(myTdmAux)
FreqMat3 <- data.frame(Term = rownames(temp), Freq = rowSums(temp))
row.names(FreqMat3) <- NULL

# remove sparse terms usuario 4
myTdmAux <- removeSparseTerms(myTdm4, sparse=0.985) 
# count frequency 
temp <- as.matrix(myTdmAux)
FreqMat4 <- data.frame(Term = rownames(temp), Freq = rowSums(temp))
row.names(FreqMat4) <- NULL

# remove sparse terms usuario 5
myTdmAux <- removeSparseTerms(myTdm5, sparse=0.985)
# count frequency
temp <- as.matrix(myTdmAux)
#View(temp)
FreqMat5 <- data.frame(Term = rownames(temp), Freq = rowSums(temp))
row.names(FreqMat5) <- NULL

```


Usuario 1
---------

```{r}
# USUARIO 1
findFreqTerms(myTdm1, lowfreq=25)
termFrequency1 <- rowSums(as.matrix(myTdm1))
termFrequency1 <- subset(termFrequency1, termFrequency1>=25)

#Impresion Grafica usuario 1
barplot(termFrequency1, las=2)
m <- as.matrix(myTdm1)
wordFreq <- sort(rowSums(m), decreasing=TRUE)
set.seed (375)
wordcloud(words = names(wordFreq), freq = wordFreq, min.freq = 8, random.order = FALSE,
          colors=brewer.pal(6, "Dark2"))
```


Usuario 2
---------

```{r}
# USUARIO 2
findFreqTerms(myTdm2, lowfreq=30)
termFrequency2 <- rowSums(as.matrix(myTdm2))
termFrequency2 <- subset(termFrequency2, termFrequency2>=30)

#Impresion Grafica usuario 2
barplot(termFrequency2, las=2)
m <- as.matrix(myTdm2)
wordFreq <- sort(rowSums(m), decreasing=TRUE)
set.seed (375)
wordcloud(words=names(wordFreq), freq=wordFreq, min.freq=10,random.order=F,
          colors=brewer.pal(6, "Dark2"))
```


Usuario 3
---------

```{r}
# USUARIO 3
findFreqTerms(myTdm3, lowfreq=35)
termFrequency3 <- rowSums(as.matrix(myTdm3))
termFrequency3 <- subset(termFrequency3, termFrequency3>=35)

#Impresion Grafica usuario 3
barplot(termFrequency3, las=2)
m <- as.matrix(myTdm3)
wordFreq <- sort(rowSums(m), decreasing=TRUE)
set.seed (375)
wordcloud(words=names(wordFreq), freq=wordFreq, min.freq=15,random.order=F,
          colors=brewer.pal(6, "Dark2"))
```


Usuario 4
---------

```{r}
# USUARIO 4
findFreqTerms(myTdm4, lowfreq=25)
termFrequency4 <- rowSums(as.matrix(myTdm4))
termFrequency4 <- subset(termFrequency4, termFrequency4>=25)

#Impresion Grafica usuario 4
barplot(termFrequency4, las=2)
m <- as.matrix(myTdm4)
wordFreq <- sort(rowSums(m), decreasing=TRUE)
set.seed (375)
wordcloud(words=names(wordFreq), freq=wordFreq, min.freq=10,random.order=F,
          colors=brewer.pal(6, "Dark2"))
```


Usuario 5
---------

```{r}
# USUARIO 5
findFreqTerms(myTdm5, lowfreq=25)
termFrequency5 <- rowSums(as.matrix(myTdm5))
termFrequency5 <- subset(termFrequency5, termFrequency5>=25)

#Impresion Grafica usuario 5
barplot(termFrequency5, las=2)
m <- as.matrix(myTdm5)
wordFreq <- sort(rowSums(m), decreasing=TRUE)
set.seed (375)
wordcloud(words=names(wordFreq), freq=wordFreq, min.freq=3,random.order=F,
          colors=brewer.pal(6, "Dark2"))
```

